### ISSUE TITLE
Question: Support?

### ISSUE THREAD

**Issue by garretttaco** [scott-wyatt/trailpack-stripe#82]
Hey, this is an awesome repo! I would like to know what your plan is for support? I noticed that the last commit you made was four months from this comment. Are you actively using this and planning on maintaining it?

**Comment by scott-wyatt** [comment]
Hi @garretttaco sorry for the delay! I'm pretty busy, but I am totally up for PRs and will publish updates quickly if need be. I have one project using it currently.
